"""Generate identical compact grayscale idle assets for Canvas and ESP32.

Only three feature windows are sampled; no phone UI or full-screen video is
included. Keep the existing 30px eye radius and face anchors. All timings are
presentation timestamps from the user's recording, not inferred randomness.
"""
import base64
import hashlib
import json
import sys
from pathlib import Path
import av
import numpy as np
from PIL import Image

root=Path(__file__).resolve().parents[1]
video=Path(sys.argv[1])
out=root/'tools/ouo-preview'
windows=[(378,241,858,661,84),(1543,241,2023,661,84),(960,450,1440,950,100)]
unique={}; blobs=[]; offsets=[0]; timeline=[]; previous=-1
def rle(data):
    encoded=bytearray(); last=int(data[0]); run=0
    for value in data:
        value=int(value)
        if value!=last or run==255:
            encoded.extend((run,last)); run=0;last=value
        run+=1
    encoded.extend((run,last))
    return encoded

with av.open(str(video)) as recording:
    stream=recording.streams.video[0]
    duration=round(float(stream.duration*stream.time_base)*1000)
    for frame in recording.decode(video=0):
        picture=frame.to_image().convert('L')
        tiles=[]
        for x0,y0,x1,y1,height in windows:
            small=picture.crop((x0,y0,x1,y1)).resize((96,height),Image.Resampling.LANCZOS)
            # Sixteen gray levels retain the recorded antialiasing and cheeks.
            tiles.append(((np.asarray(small,dtype=np.uint16)+8)//17).astype(np.uint8).ravel())
        pixels=np.concatenate(tiles); key=pixels.tobytes()
        frame_id=unique.get(key)
        if frame_id is None:
            frame_id=len(blobs);unique[key]=frame_id
            compressed=rle(pixels);blobs.append(compressed);offsets.append(offsets[-1]+len(compressed))
        time=round(float(frame.pts*frame.time_base)*1000)
        if frame_id!=previous:
            timeline.append([time,frame_id]);previous=frame_id

data=b''.join(blobs)
manifest={'source':video.name,'sha256':hashlib.sha256(video.read_bytes()).hexdigest(),
          'durationMs':duration,'width':96,'eyeHeight':84,'mouthHeight':100,
          'offsets':offsets,'timeline':timeline,'data':base64.b64encode(data).decode()}
(out/'idle-reference.js').write_text('// Generated by tools/build_ouo_idle_reference.py; do not hand edit.\n'
    +'const OUO_IDLE_REFERENCE='+json.dumps(manifest,separators=(',',':'))+';\n',encoding='utf8')
lines=['/* Generated from the user-provided idle recording. */','#pragma once','#include <stdint.h>',
       f'#define OUO_IDLE_DURATION_MS {duration}U',
       f'#define OUO_IDLE_EVENT_COUNT {len(timeline)}U',
       '#define OUO_IDLE_TILE_PIXELS (96U * (84U + 84U + 100U))',
       'static const uint32_t ouo_idle_offsets[] = {'+','.join(map(str,offsets))+'};',
       'static const uint32_t ouo_idle_events[][2] = {'+','.join('{%d,%d}'%tuple(x) for x in timeline)+'};',
       'static const uint8_t ouo_idle_rle[] = {']
lines += [','.join(map(str,data[i:i+96]))+',' for i in range(0,len(data),96)]
lines += ['};','']
(root/'main/ouo_idle_reference.h').write_text('\n'.join(lines),encoding='utf8')
summary={k:v for k,v in manifest.items() if k not in ('offsets','timeline','data')}
summary.update(uniqueFrames=len(blobs),events=len(timeline),compressedBytes=len(data),decodedBytes=25728)
reference=video.parent.parent/'_ouo_reference/idle_20260828'
(reference/'asset-summary.json').write_text(json.dumps(summary,indent=2),encoding='utf8')
print(json.dumps(summary,indent=2))
